# Generated by Django 6.0.4 on 2026-04-30 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_patente', models.CharField(max_length=20, unique=True)),
                ('pdf_documento', models.FileField(upload_to='patentes/pdfs/')),
                ('qr_imagen', models.ImageField(blank=True, null=True, upload_to='patentes/qrs/')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de Revisión'), ('aprobado', 'Listo para Retiro/Impresión'), ('rechazado', 'Documento Inválido')], default='pendiente', max_length=20)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('fecha_validacion', models.DateTimeField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Documento',
        ),
    ]
