# Generated by Django 6.0.4 on 2026-05-02 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0002_patente_delete_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patente',
            name='numero_patente',
            field=models.CharField(max_length=20),
        ),
    ]
